### ISSUE TITLE
awsmobile init doesn't add aws-amplify and related deps to package.json

### ISSUE THREAD

**Issue by claym** [aws/awsmobile-cli#149]
Running on Windows 10, node 10.4.0, npm 6.1.0

I'm working off [Building Serverless Mobile Applications with React Native & AWS](https://medium.com/react-native-training/building-serverless-mobile-applications-with-react-native-aws-740ecf719fce) which indicates that 'awsmobile init', at which point we

> should now see aws-amplify & aws-amplify-react-native in your package.json

However, I'm not seeing that. There are no errors in the awsmobile init output

Log, creating fresh project:
https://gist.github.com/claym/54376b5787e6791b4f1b342f6b8cf957

**Comment by UnleashedMind** [comment]
We haven't tested the CLI on node version 10.X yet. But it might not be the cause of the issue. 
In the logs, I don't see the CLI prints out the welcome message, it means the init process has not been completed successfully. 
The CLI only install dependency on aws-amplify and aws-amplify-react(-native) upon successfully initializing your project. 
It might be because you have not provided the correct aws credentials to the awsmobile-cli configuration, and your backend mobile hub project has not been created.

**Comment by claym** [comment]
I just ran it with node 8.11.2 and npm 5.6.0, and it seems to have behaved correctly. 

I used the same aws credentials.

**Comment by elorzafe** [comment]
I tested awsmobile-cli with node 10.4.0 and it works well
