### ISSUE TITLE
awsmobile creating appsync: create graphql api fails.

### ISSUE THREAD

**Issue by davidalekna** [aws/awsmobile-cli#176]
Hi, I can never successfully add appsync to my project from awsmobile CLI. 

version 1.1.5

following error occurs after awsmobile push:

`
⠼ creating appsync: create graphql api...create graphal API err [...project]

{ Error: connect ETIMEDOUT 92.242.132.24:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1161:14)
  message: 'connect ETIMEDOUT 92.242.132.24:443',
  errno: 'ETIMEDOUT',
  code: 'NetworkingError',
  syscall: 'connect',
  address: '92.242.132.24',
  port: 443,
  region: 'eu-west-2',
  hostname: 'appsync.eu-west-2.amazonaws.com',
  retryable: true,
  time: 2018-08-05T07:38:58.690Z }
appsync creation failed
{ Error: connect ETIMEDOUT 92.242.132.24:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1161:14)
  message: 'connect ETIMEDOUT 92.242.132.24:443',
  errno: 'ETIMEDOUT',
  code: 'NetworkingError',
  syscall: 'connect',
  address: '92.242.132.24',
  port: 443,
  region: 'eu-west-2',
  hostname: 'appsync.eu-west-2.amazonaws.com',
  retryable: true,
  time: 2018-08-05T07:38:58.690Z }

updating backend project: [...project]

Successfully updated the backend awsmobile project: [...project]
`

**Comment by elorzafe** [comment]
I think the issue is because AppSync is not available on EU (London) region.
Current supported regions are
US East (N. Virginia), US West (Oregon), US East (Ohio), EU (Ireland), EU (Frankfurt), Asia Pacific (Tokyo), Asia Pacific (Sydney), Asia Pacific (Mumbai) and Asia Pacific (Singapore).

You can try on eu-central-1 or eu-west-1 regions that are closer to you.

**Comment by davidalekna** [comment]
Ah right thats what I thought @elorzafe, but I don't get to choose region on the --prompt 🤔
