### ISSUE TITLE
gitignore list

### ISSUE THREAD

**Issue by rdingwell** [aws/awsmobile-cli#88]
```
#awsmobilejs
aws-info.json
project-info.json
aws-exports.js
awsmobilejs/.awsmobile/backend-build
awsmobilejs/\#current-backend-info
~awsmobilejs-*/
```
Looking at the gitignore list that is created wouldn't it be cleaner to just ignore the entire awsmobilejs directory along with the aws-exports.js file?  If multiple devs are expected to run awsmobilejs init <project_id> then that directory will be created by that command anyway.  Right now the gitignore list looks like a hodgepodge of files with no clear purpose as to why they are to be ignored.

**Comment by UnleashedMind** [comment]
Thanks @rdingwell for the feedbacks.

Unfortunately, there are scenarios that can not be address by the above suggested approach. 
Because the backend mobile hub project belongs to a specific aws account, if there are collabrators that do not have access to that specific aws account, then they wouldn't be able to init with that `<project_id>`.  

Instead, the awsmobile-cli puts all the files that contains mobile-hub project specific information in the .gitignore file , but keeps the mobile-hub project specifications inside the `awsmobilejs/backend` folder.  So the collaborators have the options to: 
- `awsmobile init <project_id>` : if he has access to an existing backend mobile hub project
- `awsmobile init`: if he does not have access to any existing backend awsmobile project, or he wants to create a new awsmobile project as the backend. 

The awsmobile-cli can detect that valid awsmobile project specifications are inside the `awsmobile/backend` folder, and allow the developer to create the new awsmobile project using the existing specifications.
